# Generated by Django 2.2.11 on 2020-04-28 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 1, 23, 42, 780787)),
        ),
    ]
