# Generated by Django 2.2.11 on 2020-05-14 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_auto_20200429_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 16, 31, 255282)),
        ),
    ]
