# Generated by Django 2.2.11 on 2020-05-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_kullanicilar_image'),
        ('Market', '0003_auto_20200514_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpgrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kullanici_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Kullanicilar')),
                ('Market_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.Market')),
            ],
        ),
    ]
