# Generated by Django 2.2.11 on 2020-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Sifre', models.CharField(max_length=16, verbose_name='Şifre')),
                ('Kullanici_Adi', models.CharField(max_length=16, verbose_name='Kullanıcı Adı')),
                ('Yetki', models.CharField(default='Kullanıcı', max_length=16, verbose_name='Yetki')),
                ('Ad', models.CharField(max_length=32, verbose_name='Ad')),
                ('Soyad', models.CharField(max_length=32, verbose_name='Soyad')),
            ],
        ),
    ]
