# Generated by Django 2.2.11 on 2020-04-27 22:16

import Market.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_kullanicilar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128, verbose_name='Başlık')),
                ('Price', models.IntegerField(verbose_name='Ücret')),
                ('Status', models.CharField(max_length=128, verbose_name='Ürün Durumu')),
                ('Description', models.CharField(max_length=512, verbose_name='Açıklama')),
                ('Category', models.CharField(max_length=128, verbose_name='Kategori')),
                ('Longitude', models.FloatField(verbose_name='Boylam')),
                ('Latitude', models.FloatField(verbose_name='Enlem')),
                ('Date', models.DateTimeField(default=datetime.datetime(2020, 4, 28, 1, 16, 25, 249130))),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Kullanicilar')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(null=True, upload_to=Market.models.Images.get_upload_path, verbose_name='Resim')),
                ('Market_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.Market')),
            ],
        ),
    ]
