# Generated by Django 2.2.11 on 2020-04-28 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_kullanicilar_image'),
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 1, 23, 42, 787982)),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.Market')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Kullanicilar')),
            ],
        ),
    ]
