# Generated by Django 2.2.11 on 2020-05-22 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20200514_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 1, 31, 51, 844423)),
        ),
    ]
