# Generated by Django 2.2.11 on 2020-03-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='New',
        ),
    ]
