# Generated by Django 2.2.11 on 2020-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_remove_activities_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='Latitude',
            field=models.FloatField(null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='activities',
            name='Longitude',
            field=models.FloatField(null=True, verbose_name='Boylam'),
        ),
    ]
