# Generated by Django 2.2.11 on 2020-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(verbose_name='Boylam')),
                ('Latitude', models.FloatField(verbose_name='Enlem')),
                ('Activity_Id', models.IntegerField(verbose_name='Etkinlik id')),
            ],
        ),
    ]
