# Generated by Django 2.2.11 on 2020-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='Activity_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activities.Activities'),
        ),
    ]
