# Generated by Django 2.2.11 on 2020-03-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Like', models.IntegerField(default=0)),
                ('Dislike', models.IntegerField(default=0)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Kullanicilar')),
            ],
        ),
    ]
